import type { Character } from '../types/game';

export const characters: Record<string, Character> = {
  warrior: {
    id: 'warrior',
    name: '战士',
    unlocked: true,
    color: 0xff6b6b,
    stats: {
      hp: 100,
      maxHp: 100,
      mp: 50,
      maxMp: 50,
      attack: 20,
      defense: 10,
      speed: 5,
      jumpForce: 15,
    },
    skill: {
      name: '旋风斩',
      damage: 40,
      cooldown: 5000,
      mpCost: 20,
      range: 80,
    },
  },
  mage: {
    id: 'mage',
    name: '法师',
    unlocked: false,
    color: 0x6b9fff,
    stats: {
      hp: 70,
      maxHp: 70,
      mp: 100,
      maxMp: 100,
      attack: 15,
      defense: 5,
      speed: 4,
      jumpForce: 12,
    },
    skill: {
      name: '火球术',
      damage: 50,
      cooldown: 4000,
      mpCost: 30,
      range: 200,
    },
  },
  archer: {
    id: 'archer',
    name: '弓箭手',
    unlocked: false,
    color: 0x6bff9f,
    stats: {
      hp: 80,
      maxHp: 80,
      mp: 70,
      maxMp: 70,
      attack: 25,
      defense: 7,
      speed: 6,
      jumpForce: 14,
    },
    skill: {
      name: '多重射击',
      damage: 35,
      cooldown: 3500,
      mpCost: 25,
      range: 250,
    },
  },
  ninja: {
    id: 'ninja',
    name: '忍者',
    unlocked: false,
    color: 0x9f6bff,
    stats: {
      hp: 75,
      maxHp: 75,
      mp: 80,
      maxMp: 80,
      attack: 30,
      defense: 5,
      speed: 8,
      jumpForce: 18,
    },
    skill: {
      name: '影袭',
      damage: 60,
      cooldown: 6000,
      mpCost: 35,
      range: 100,
    },
  },
};
