import type { MonsterConfig } from '../types/game';

export const monsters: Record<string, MonsterConfig> = {
  slime: {
    id: 'slime',
    name: '史莱姆',
    type: 'normal',
    color: 0x6bff9f,
    hp: 30,
    attack: 10,
    speed: 1.5,
    width: 32,
    height: 32,
    patrolRange: 100,
    chaseRange: 150,
    attackRange: 40,
    attackCooldown: 1500,
    dropRate: 0.3,
  },
  goblin: {
    id: 'goblin',
    name: '哥布林',
    type: 'normal',
    color: 0x9f6b4f,
    hp: 50,
    attack: 15,
    speed: 2.5,
    width: 36,
    height: 48,
    patrolRange: 150,
    chaseRange: 200,
    attackRange: 50,
    attackCooldown: 1200,
    dropRate: 0.4,
  },
  skeleton: {
    id: 'skeleton',
    name: '骷髅弓手',
    type: 'ranged',
    color: 0xf0f0f0,
    hp: 40,
    attack: 20,
    speed: 1,
    width: 32,
    height: 48,
    patrolRange: 100,
    chaseRange: 250,
    attackRange: 200,
    attackCooldown: 2000,
    dropRate: 0.5,
  },
  darkMage: {
    id: 'darkMage',
    name: '暗黑法师',
    type: 'ranged',
    color: 0x6b4f9f,
    hp: 60,
    attack: 25,
    speed: 0.8,
    width: 36,
    height: 52,
    patrolRange: 80,
    chaseRange: 300,
    attackRange: 250,
    attackCooldown: 2500,
    dropRate: 0.6,
  },
  boss1: {
    id: 'boss1',
    name: '巨型史莱姆王',
    type: 'boss',
    color: 0x4fff7f,
    hp: 300,
    attack: 30,
    speed: 1.2,
    width: 80,
    height: 80,
    patrolRange: 200,
    chaseRange: 400,
    attackRange: 80,
    attackCooldown: 1800,
    dropRate: 1,
  },
  boss2: {
    id: 'boss2',
    name: '骷髅领主',
    type: 'boss',
    color: 0xcfcfcf,
    hp: 500,
    attack: 40,
    speed: 1.5,
    width: 70,
    height: 90,
    patrolRange: 250,
    chaseRange: 500,
    attackRange: 100,
    attackCooldown: 1500,
    dropRate: 1,
  },
};
